{
    tokens = [
//        DOLLAR = '$'
//        AT = '@'
        BRACE = 'regexp:[{}]'
        WHITE_SPACE = 'regexp:\s+'
//        BRACED_VARIABLE_NAME = 'regexp:([^}`]|`.)+'
//        BRACED_VARIABLE_NAME = 'regexp:[^}`]+'
//        VARIABLE_NAME = 'regexp:[\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nd}_?]+'
//        BRACED_VARIABLE = 'regexp:\$\{[^}]+}'
//        BRACED_VARIABLE_START = 'regexp:\$\{'
//        BRACED_VARIABLE_END = 'regexp:}'
    ]
}

root ::= (variable)*

variable ::=
    '{' 'regexp:[^}`]+' '}'
//   '$$' | '$?' | '$^'| '$_'
//  | ('$' | '@') variable-scope? variable-characters
//   braced-variable

//braced-variable ::=
//    '${' variable-scope?  braced-variable-characters '}'
//    '${' braced-variable-characters '}'
//    'regexp:\$\{' 'regexp:([^}`]|`.)+' '}'
//    'regexp:\$\{' 'regexp:([^}`])+' '}'
//    'regexp:\$\{[^}`]+}'
//    '{' 'regexp:[^}`]+' '}'

//private variable-characters ::=
//    VARIABLE_NAME

//private braced-variable-characters ::=
//    'regexp:([^}`]|`.)+'
////    BRACED_VARIABLE_NAME
//
//variable-scope ::=
//    'global:'
//  | 'local:'
//  | 'private:'
//  | 'script:'
//  | 'using:'
//  | 'workflow:'
//  | variable-namespace
//
//variable-namespace ::=
//    variable-characters ':'

