{
    tokens = [
        WHITE_SPACE = 'regexp:\s+'
        VARIABLE_CHARS = 'regexp:[\p{Lu}\p{Ll}\p{Lt}\p{Lm}\p{Lo}\p{Nd}_?]+'
        DOLLAR = '$'
    ]
}

root ::= (variable)*

variable ::=
   '$$' | '$?' | '$^'| '$_'
  | ('$' | '@') variable-scope? variable-characters

variable-characters ::=
    VARIABLE_CHARS

variable-scope ::=
    'global:'
  | 'local:'
  | 'private:'
  | 'script:'
  | 'using:'
  | 'workflow:'
  | variable-namespace

variable-namespace ::=
    variable-characters ':'
